
import { Component } from '@angular/core';

@Component({
  selector: 'app-season-info',
  templateUrl: './season-info.component.html',
  styleUrls: ['./season-info.component.css']
})

export class SeasonInfoComponent {
  title = "Game of Thrones"
  overview = `
  On the edge of the promised land dust storms rise out of the desert, obscuring everything, even the migrants waiting at the gate in front of a complex surrounded by a chain-linked fence topped by barbed wire. But Father Javier Calvillo Salazar is from Juárez, Mexico and he is used to it all, and to those who arrive after what is sometimes thousands of miles and hundreds of days with a collection of scars, broken bones, and missing limbs to match the inhumanity encountered along the way. They arrive weeping, they arrive stony-faced, they arrive pregnant, they arrive with venereal diseases—sometimes they arrive telling García Márquez-esqe stories of witnessing a crocodile eat a newborn baby in one swift bite.

Nicole was delivered at a hospital into the arms of her mother, Ana Lizbeth Bonía, 28, who arrived at the shelter in Juárez after spending nine months traveling north from Comayagua, Honduras. She showed up at the migrant shelter Casa del Migrante Diócesis de Ciudad Juárez with her husband Luis Orlando Rubí, 23, and her underweight son, José Luis, 2, who had saucer-like eyes that glistened with emotion. Ana, who had grown up selling vegetables in the street since the age of 4, had never finished elementary school.

The migrant shelter in Juárez is so close to El Paso, Texas that migrants feel the bittersweet pull of land they can see but likely never legally inhabit. The shelter has 120 beds for men, 60 for women, 20 for families, and one separate area where transgender migrants can stay if they choose. Most migrants who arrive at the shelter are single men, and in interviews migrants mentioned that President Trump’s threat of separating women from their children had led to a decrease in migration by those groups. Each migrant is initially limited to a three-day stay, but they can extend that time depending on their condition, as in the case of Ana, who needed time to rest and recuperate after giving birth to Nicole. 
The shelter was open in 1982 by the Missionaries of San Carlos, and Father Javier has been its director for seven years and working with migrants for 15. A staff of 23 including therapists, human rights experts, cooks, and receptionists helps run the migrant shelter 24 hours a day, seven days a week. In January the Catholic Church assigned Father Ricardo Reina García, 42, to support Father Javier’s work at the shelter, and when I arrived he had been there for almost two months.

I had been traveling to Juárez since 2011, first as a part of interviews for my book, More or Less Dead, and later because I could never stop writing about the women I met, mothers whose daughters were victims of disappearance, rape and murder. I wanted to use my words to fight for justice and equality. What I learned from the research process of my book was that many of the victims of violence in Juárez were migrants, because migrants, who are often undocumented and far from extended family, are extremely vulnerable to violence. After my book was published in 2015, I knew that my next project would tell the stories of migrants, many of whom disappeared without a trace in Mexico, victims of an extensive network of human trafficking. In 2017, I received a fellowship to embark on a six-month project about Central American migrants, and I returned to Juárez to live in the city’s migrant shelter as the first leg of a journey in which I would later follow the migrant trail through Mexico, Guatemala and El Salvador.

Three days after Ana’s arrival at the migrant shelter in Juárez, Father Ricardo rushed Ana to the hospital to give birth. Before getting in the van, Father Ricardo said that Ana told him that she didn’t want her husband Luis to be present in the delivery room.

Father Ricardo, who was born in Juárez, is big in a way that could be intimidating if he weren’t so soft-spoken. His voice is a soothing, a notch above a whisper, and he spends his days presiding over baptisms, weddings, and funerals in between ferrying migrants to the bus station, medical appointments, and work assignments. During my two weeks living at the shelter, we spent a lot of time together. One sunny afternoon, as the wind was whipped around the corners of the shelter outside, he said, “My family context means that I understand the dynamics of migration. My dad is from a ranch in Zaragoza, my mom is from Zacatecas, and my grandmother on my mom’s side is from Durango. My roots are in human mobility, which means looking for a better life for future generations. I believe that migration is a human condition that will always be present.”

For some migrants, the road ended in Juárez, where at least work was readily available. When Nicole was five days old, I sat down with her father Luis, to ask about his journey. He and Ana had taken buses all the way from their home in Honduras to Juárez, and whenever they ran out of money, they stayed in one place and begged in the street or found work. He said, “We wanted to cross to the United States, but according to what the President said, he is going to separate parents from their children, so we changed our plans and decided to stay here.” Luis, despite his youth, seemed confident about building a life in Juárez for his wife and two young kids.

At the migrant shelter, one mother, Ana, had given birth while another mother wondered where her daughter might be. Anahí Ortigoza Reyes, 34, was stuck in Juárez, while her daughter, 4-year-old Ashley Anahí, was in Oregon. Anahí and Ashley Anahí had flown to Juárez from Huajuapan de León, México. Anahí told me she had hired smugglers to get herself and her daughter across the border, but they had been forced to separate. The smugglers took her daughter safely across first, but left Anahí near the border wall with a pair of wire cutters, and told her she had to cut her way through several chain-link fences. Almost immediately, Anahí was caught by border patrol agents and sent back to Juárez. “My husband is on the other side,” she told me. “He lives in Oregon. My daughter is already in Oregon.” I asked Anahí when she had last lived in the U.S. “I returned to Mexico, and I’ve been here 12 years. I came to see my mother was sick,” she said.

Manuel García Corona, 45, who was born in Michoacán, Mexico, arrived at the shelter after being deported from the U.S. He had been living there for 25 years, and he worked as a truck driver despite his undocumented status. When I asked him why he had been deported, he said he had been wrongly accused of transporting undocumented migrants, but he didn’t want to discuss the details. “Return to the USA?” he asked. “It is a very beautiful country and the people are patient, and I appreciate their patience in communicating with me, but for those of us who have already deported, it is a country of fear. I would call it hell.” Manuel planned to return to his home state of Michoacán, Mexico rather than to attempt to enter the U.S. again. Other deported men who showed up at the shelter spoke of children left behind in the U.S., of families split apart—and they said they would cross the border as many times as it took to be reunited with their sons and daughters.
    `
}
