INSERT INTO genre(genre) VALUES ("Action");
INSERT INTO genre(genre) VALUES ("Adventure");
INSERT INTO genre(genre) VALUES ("Animation");
INSERT INTO genre(genre) VALUES ("Anime");
INSERT INTO genre(genre) VALUES ("Biography");
INSERT INTO genre(genre) VALUES ("Children");
INSERT INTO genre(genre) VALUES ("Comedy");
INSERT INTO genre(genre) VALUES ("Crime");
INSERT INTO genre(genre) VALUES ("Disaster");
INSERT INTO genre(genre) VALUES ("Documentary");
INSERT INTO genre(genre) VALUES ("Drama");
INSERT INTO genre(genre) VALUES ("Eastern");
INSERT INTO genre(genre) VALUES ("Family");
INSERT INTO genre(genre) VALUES ("Fan Film");
INSERT INTO genre(genre) VALUES ("Fantasy");
INSERT INTO genre(genre) VALUES ("Film Noir");
INSERT INTO genre(genre) VALUES ("Game Show");
INSERT INTO genre(genre) VALUES ("History");
INSERT INTO genre(genre) VALUES ("Holiday");
INSERT INTO genre(genre) VALUES ("Home And Garden");
INSERT INTO genre(genre) VALUES ("Horror");
INSERT INTO genre(genre) VALUES ("Indie");
INSERT INTO genre(genre) VALUES ("Mini Series");
INSERT INTO genre(genre) VALUES ("Music");
INSERT INTO genre(genre) VALUES ("Musical");
INSERT INTO genre(genre) VALUES ("Mystery");
INSERT INTO genre(genre) VALUES ("News");
INSERT INTO genre(genre) VALUES ("None");
INSERT INTO genre(genre) VALUES ("Reality");
INSERT INTO genre(genre) VALUES ("Road");
INSERT INTO genre(genre) VALUES ("Romance");
INSERT INTO genre(genre) VALUES ("Science Fiction");
INSERT INTO genre(genre) VALUES ("Short");
INSERT INTO genre(genre) VALUES ("Soap");
INSERT INTO genre(genre) VALUES ("Special Interest");
INSERT INTO genre(genre) VALUES ("Sporting Event");
INSERT INTO genre(genre) VALUES ("Sports");
INSERT INTO genre(genre) VALUES ("Suspense");
INSERT INTO genre(genre) VALUES ("Talk Show");
INSERT INTO genre(genre) VALUES ("Thriller");
INSERT INTO genre(genre) VALUES ("Tv Movie");
INSERT INTO genre(genre) VALUES ("War");
INSERT INTO genre(genre) VALUES ("Western");
